### ISSUE TITLE
How to modify the size of epoch at training?

### ISSUE THREAD

**Issue by lassdaf123** [ThomasMrY/DisDiff#1]
Hello, author. I'm trying to run your code and am currently training VAE, but I'm running into a problem (although this issue doesn't affect the normal use of the code), please how can I modify the size of epoch at training, I look at the prompt terminal while training shows its default training epoch=1000, it's a bit too time-consuming for me. Thank you for replying to me in your busy schedule and look forward to your answer

**Comment by ThomasMrY** [comment]
Hi lassdaf123,
Thank you for interesting at our project, you can set the max_epochs in the training config files
For pytorch lighting the default argments is:
# DEFAULT
trainer = Trainer(min_epochs=1, max_epochs=1000)
By set this parameter, you can change any training epoch number you want:
  trainer:
    benchmark: True
    max_epochs=the epoch number you want.

Thanks,
Tao

**Comment by lassdaf123** [comment]
Thank you very much。
