### ISSUE TITLE
The problem of .gitignore file

### ISSUE THREAD

**Issue by SomunsmM** [ThomasMrY/DisDiff#3]
Hello author, I found that the. gitignore file is missing from the project while running your code. I would like to inquire about the specific content in this file and whether it will affect training or testing. Or could you please upload this file?

**Comment by ZiQ-Li** [comment]
This file does not seem to affect the training or testing process, but the more serious problem is the lack of some operating codes during the training or testing phase.

**Comment by SomunsmM** [comment]
Yes, I found this issue.

**Comment by ThomasMrY** [comment]
Hi SomunsmM,
.gitignore is a file that specify these files that should be ignored when upload the code to github, I will update a version today, including the .ignore file.
Thanks,
Tao
