### ISSUE TITLE
Questions about the pretrained model

### ISSUE THREAD

**Issue by ZiQ-Li** [ThomasMrY/DisDiff#5]
Dear authors, Is the pre-trained model trained based on the FFHQ dataset or else? it seems that just one pre-trained model (just trained on a special dataset) is provided.

**Comment by ThomasMrY** [comment]
These model will be released in near future.

**Comment by WonwoongCho** [comment]
Hi @ThomasMrY ,

Thank you for sharing your awesome work.
I was wondering if you have released the pertained models trained on facial datasets (e.g., celeba or ffhq) somewhere.

Thanks
